# Generated by Django 3.2 on 2022-02-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='PatientEmail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
