# Generated by Django 3.2 on 2021-12-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_patients_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
                ('speciality', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('timeOfAvailability', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('EmailAddress', models.EmailField(max_length=254, unique=True)),
                ('experince', models.CharField(max_length=15)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
