# Generated by Django 3.2 on 2022-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20220219_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='active',
            field=models.CharField(default='yes', max_length=10),
        ),
    ]
