# Generated by Django 3.2 on 2021-12-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20211227_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='timeOfAvailability',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availableFrom',
            field=models.CharField(default=9, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='availableTo',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experince',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
