# Generated by Django 3.2 on 2021-12-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20211228_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.IntegerField(max_length=20),
        ),
    ]
