# Generated by Django 3.2 on 2022-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220228_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.FileField(default='doc-2.jpg', upload_to='images'),
        ),
    ]
