# Generated by Django 3.2 on 2022-03-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_department_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientEmail', models.CharField(max_length=100)),
                ('PatientName', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('RBCCount', models.CharField(max_length=50)),
                ('Hemoglobin', models.CharField(max_length=50)),
                ('Hematocrit', models.CharField(max_length=50)),
                ('WBCcount', models.CharField(max_length=50)),
                ('Platelet', models.CharField(max_length=50)),
                ('Appoitment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.appoitment')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
