# Generated by Django 3.2 on 2021-12-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_doctor_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instragram',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
