# Generated by Django 3.2 on 2022-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_mrireport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrireport',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
