# Generated by Django 3.2 on 2021-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20211228_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
