# Generated by Django 3.2 on 2022-03-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_mrireport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrireport',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
