# Generated by Django 3.2 on 2022-01-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_appoitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availableFrom',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availableTo',
            field=models.TimeField(),
        ),
    ]
