# Generated by Django 3.2 on 2022-01-18 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0011_auto_20220118_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitment',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appoitment',
            name='department',
            field=models.CharField(choices=[('ENT (Ear-Nose-Throat)', 'ENT (Ear-Nose-Throat)'), ('Ophthalmologists', 'OPHTHALMOLOGISTS'), ('Neurologists', 'NEUROLOGISTS'), ('pulmonologists', 'PULMONOLOGISTS')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('ENT (Ear-Nose-Throat)', 'ENT (Ear-Nose-Throat)'), ('Ophthalmologists', 'OPHTHALMOLOGISTS'), ('Neurologists', 'NEUROLOGISTS'), ('pulmonologists', 'PULMONOLOGISTS')], default='General', max_length=100),
        ),
    ]
