# Generated by Django 3.2 on 2022-01-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20220118_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='PatientName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
