# Generated by Django 3.2 on 2022-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20220409_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrireport',
            name='normalPercent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrireport',
            name='tumorPercent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
