# Generated by Django 3.2 on 2022-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_appoitment_patientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='DoctorEmail',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
