# Generated by Django 3.2 on 2022-02-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitment',
            name='DoctorFullName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
