# Generated by Django 3.2 on 2022-04-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
