# Generated by Django 3.2 on 2022-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='avatar.svg', upload_to='images'),
        ),
    ]
