# Generated by Django 3.2 on 2022-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='/static/image/avatar.svg', upload_to='images'),
        ),
    ]
